
export const dropdownFields = {
    status: 'Status',
    type: 'Type',
    rooms: 'Size',
    floor: 'Floor',
    construction: 'Construction Type',
    bedrooms: 'Bedrooms',
    bathrooms: 'Bathrooms',
    heating: 'Heating',
}

export const initialData = {
    title: '',
    description: '',
    status: 'Status',
    property_type: 'Type',
    rooms: 'Size',
    price: '',
    square_feet: '',
    build: '',
    address: '',
    city: '',
    state: '',
    country: '',
    latitude: '',
    longitude: '',
    floor: 'Floor',
    construction: 'Construction Type',
    bedrooms: 'Bedrooms',
    bathrooms: 'Bathrooms',
    heating: 'Heating',
    features: [],
    images: [],
    video: '',
    floorPlans: [],
    // inConstruction: false,
    // garage: false,
    // swimmingPool: false,
    // furnished: false,
    // parking: false,
    // gym: false,
    // alarm: false,
    // windowCovering: false,
    // guard: false,
    // tv_wifi: false,
    // renovated: false,
    // yard: false,
    name: '',
    username: '',
    email: '',
    phone: '',
}
